server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related docker APIs"
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235
