spring:
  application:
    name: "gatewayserver"
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: unrestricted

info:
  app:
    name: "gatewayserver"
    description: "Eazy Bank Gatewayserver Application"
    version: "1.0.0"
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/

logging:
  level:
    com:
      eazybytes:
        gatewayserver: DEBUG
